import type { Exercise, Skill, SkillCategory } from './types';

export const skillCategories: SkillCategory[] = [
  { id: 'cyber-foundations', title: 'Cyber Foundations', description: 'Safe defensive vocabulary, ethics, risk, and the CIA triad.', order: 1 },
  { id: 'identity-access', title: 'Identity and Access', description: 'Authentication, authorization, MFA, least privilege, and access reviews.', order: 2 },
  { id: 'networking-cybersecurity', title: 'Networking for Cybersecurity', description: 'IP, DNS, HTTP/S, ports, logs, and network-flow interpretation.', order: 3 },
  { id: 'linux-systems', title: 'Linux and Systems Basics', description: 'Files, permissions, processes, users, groups, command line, and logs.', order: 4 },
  { id: 'blue-team-soc', title: 'Blue Team / SOC Foundations', description: 'Alerts, log analysis, triage, incident notes, escalation, and evidence handling.', order: 5 },
  { id: 'web-security-defense', title: 'Web Security Defense', description: 'Web app concepts, sessions, access control, input validation, remediation, and safe code review.', order: 6 },
  { id: 'cloud-iam-defense', title: 'Cloud and IAM Defense', description: 'Cloud basics, IAM roles, secrets, misconfiguration review, and least-privilege design.', order: 7 },
  { id: 'grc-risk', title: 'GRC and Risk', description: 'Risk registers, control mapping, privacy, continuity, and executive summaries.', order: 8 },
  { id: 'ai-security-awareness', title: 'AI Security Awareness', description: 'Safe AI use, private-data boundaries, prompt safety, limitations, and classroom rules.', order: 9 }
];

export const skillCatalog: Skill[] = [
  { id: 'cyber-what-is-cybersecurity', title: 'What is cybersecurity?', categoryId: 'cyber-foundations', categoryTitle: 'Cyber Foundations', description: 'Explain cybersecurity as authorized protection of people, systems, and data.', prerequisites: [], lessonSlugs: ['what-is-cybersecurity'], exerciseIds: ['ex-cyber-scope-1'], labSlugs: [], portfolioArtifact: 'Defensive learning pledge', trackSlug: 'cyber-foundations', reviewCadenceDays: 7 },
  { id: 'cyber-cia-triad', title: 'CIA Triad', categoryId: 'cyber-foundations', categoryTitle: 'Cyber Foundations', description: 'Classify confidentiality, integrity, and availability trade-offs in safe scenarios.', prerequisites: ['cyber-what-is-cybersecurity'], lessonSlugs: ['cia-triad'], exerciseIds: ['ex-cia-classify-1'], labSlugs: ['digital-safety-home-audit'], portfolioArtifact: 'CIA triad mini-analysis', trackSlug: 'cyber-foundations', reviewCadenceDays: 10 },
  { id: 'cyber-risk-basics', title: 'Assets, threats, vulnerabilities, and risk', categoryId: 'cyber-foundations', categoryTitle: 'Cyber Foundations', description: 'Separate assets, threats, vulnerabilities, impact, likelihood, and safe treatment.', prerequisites: ['cyber-cia-triad'], lessonSlugs: ['risk-assets-threats'], exerciseIds: ['ex-risk-ranking-1'], labSlugs: ['risk-register-review'], portfolioArtifact: 'Toy risk register', trackSlug: 'cyber-foundations', reviewCadenceDays: 10 },
  { id: 'cyber-ethics-authorization', title: 'Ethics and authorization', categoryId: 'cyber-foundations', categoryTitle: 'Cyber Foundations', description: 'Apply authorization boundaries and refuse real-target or harmful activity.', prerequisites: ['cyber-what-is-cybersecurity'], lessonSlugs: ['what-is-cybersecurity'], exerciseIds: ['ex-ethics-boundary-1'], labSlugs: [], portfolioArtifact: 'Authorization checklist', trackSlug: 'cyber-foundations', reviewCadenceDays: 14 },
  { id: 'iam-authentication', title: 'Authentication', categoryId: 'identity-access', categoryTitle: 'Identity and Access', description: 'Describe how accounts prove identity without collecting or testing real credentials.', prerequisites: ['cyber-ethics-authorization'], lessonSlugs: ['identity-access-basics'], exerciseIds: ['ex-authn-authz-1'], labSlugs: ['password-policy-audit'], portfolioArtifact: 'Account safety checklist', trackSlug: 'identity-and-access', reviewCadenceDays: 10 },
  { id: 'iam-authorization', title: 'Authorization and least privilege', categoryId: 'identity-access', categoryTitle: 'Identity and Access', description: 'Decide what access is appropriate for fictional roles and document least-privilege changes.', prerequisites: ['iam-authentication'], lessonSlugs: ['identity-access-basics'], exerciseIds: ['ex-least-privilege-1'], labSlugs: ['access-control-review', 'mock-cloud-iam-review'], portfolioArtifact: 'Access review memo', trackSlug: 'identity-and-access', reviewCadenceDays: 14 },
  { id: 'iam-mfa-passwords', title: 'MFA and password security', categoryId: 'identity-access', categoryTitle: 'Identity and Access', description: 'Recommend safe password and MFA policy improvements for fictional organizations.', prerequisites: ['iam-authentication'], lessonSlugs: ['passwords-mfa-and-phishing'], exerciseIds: ['ex-mfa-policy-1'], labSlugs: ['password-policy-audit'], portfolioArtifact: 'Password policy audit memo', trackSlug: 'identity-and-access', reviewCadenceDays: 14 },
  { id: 'net-ip-dns-http', title: 'IP, DNS, and HTTP/HTTPS basics', categoryId: 'networking-cybersecurity', categoryTitle: 'Networking for Cybersecurity', description: 'Interpret toy network records and identify defensive observations.', prerequisites: ['cyber-risk-basics'], lessonSlugs: ['networking-fundamentals'], exerciseIds: ['ex-dns-http-log-1'], labSlugs: ['network-log-triage'], portfolioArtifact: 'Network observation note', trackSlug: 'soc-analyst', reviewCadenceDays: 10 },
  { id: 'net-logs-flows', title: 'Logs and network flow interpretation', categoryId: 'networking-cybersecurity', categoryTitle: 'Networking for Cybersecurity', description: 'Read fictional logs, select evidence, and write safe triage notes.', prerequisites: ['net-ip-dns-http'], lessonSlugs: ['networking-fundamentals'], exerciseIds: ['ex-log-evidence-1'], labSlugs: ['network-log-triage'], portfolioArtifact: 'Log triage note', trackSlug: 'soc-analyst', reviewCadenceDays: 7 },
  { id: 'linux-files-permissions', title: 'Files, permissions, users, and groups', categoryId: 'linux-systems', categoryTitle: 'Linux and Systems Basics', description: 'Explain safe permission concepts using toy examples and defensive reasoning.', prerequisites: ['cyber-ethics-authorization'], lessonSlugs: ['operating-systems-and-files', 'linux-windows-basics'], exerciseIds: ['ex-linux-permissions-1'], labSlugs: ['linux-permissions-detective'], portfolioArtifact: 'Permissions explanation card', trackSlug: 'security-engineering', reviewCadenceDays: 14 },
  { id: 'soc-alert-triage', title: 'Alerts, triage, and incident notes', categoryId: 'blue-team-soc', categoryTitle: 'Blue Team / SOC Foundations', description: 'Classify fictional alerts, pick evidence, and write escalation-ready notes.', prerequisites: ['net-logs-flows'], lessonSlugs: ['soc-alert-triage'], exerciseIds: ['ex-alert-triage-1'], labSlugs: ['first-soc-alert-triage'], portfolioArtifact: 'Incident triage note', trackSlug: 'soc-analyst', reviewCadenceDays: 7 },
  { id: 'web-access-input-defense', title: 'Access control and input validation defense', categoryId: 'web-security-defense', categoryTitle: 'Web Security Defense', description: 'Review toy app behavior and recommend defensive remediation without exploit steps.', prerequisites: ['iam-authorization'], lessonSlugs: ['browser-and-web-basics', 'web-security-defense'], exerciseIds: ['ex-web-remediation-1'], labSlugs: ['safe-code-review'], portfolioArtifact: 'Secure remediation memo', trackSlug: 'application-security', reviewCadenceDays: 14 },
  { id: 'cloud-iam-roles', title: 'Cloud IAM roles and secrets', categoryId: 'cloud-iam-defense', categoryTitle: 'Cloud and IAM Defense', description: 'Spot fictional over-permissioning and secret-handling risks, then scope safer roles.', prerequisites: ['iam-authorization'], lessonSlugs: ['cloud-iam-basics'], exerciseIds: ['ex-cloud-iam-1'], labSlugs: ['mock-cloud-iam-review'], portfolioArtifact: 'Cloud IAM review memo', trackSlug: 'cloud-security', reviewCadenceDays: 14 },
  { id: 'grc-risk-registers', title: 'Risk registers and executive summaries', categoryId: 'grc-risk', categoryTitle: 'GRC and Risk', description: 'Prioritize fictional risks and communicate defensible actions to non-technical stakeholders.', prerequisites: ['cyber-risk-basics'], lessonSlugs: ['risk-registers-and-controls'], exerciseIds: ['ex-exec-summary-1'], labSlugs: ['risk-register-review'], portfolioArtifact: 'Executive risk summary', trackSlug: 'grc-risk', reviewCadenceDays: 21 },
  { id: 'ai-safe-use-boundaries', title: 'Safe AI use and private-data boundaries', categoryId: 'ai-security-awareness', categoryTitle: 'AI Security Awareness', description: 'Classify acceptable classroom AI use while protecting privacy and authorization boundaries.', prerequisites: ['cyber-ethics-authorization'], lessonSlugs: ['ai-security-awareness'], exerciseIds: ['ex-ai-boundary-1'], labSlugs: ['ai-security-awareness-scenario'], portfolioArtifact: 'Classroom AI rules summary', trackSlug: 'ai-security-awareness', reviewCadenceDays: 14 }
];

export const exerciseCatalog: Exercise[] = [
  { id: 'ex-cyber-scope-1', skillId: 'cyber-what-is-cybersecurity', type: 'multiple_choice', difficulty: 1, mode: 'learn', prompt: 'Which answer best describes safe cybersecurity learning?', scenario: 'A student cyber club is starting its first week.', options: ['Protect systems with authorization and fictional practice data', 'Try techniques against random websites', 'Collect classmates’ passwords to test strength', 'Bypass school controls to learn faster'], correctAnswer: 'Protect systems with authorization and fictional practice data', explanation: 'CyberPath practice is defensive-only, authorized, and uses toy or fictional data.', hints: ['Look for authorization.', 'Avoid real targets and private data.'], commonWrongAnswerExplanation: 'Anything involving real targets, passwords, or bypassing systems is outside the safety boundary.', relatedLessonSlug: 'what-is-cybersecurity' },
  { id: 'ex-cia-classify-1', skillId: 'cyber-cia-triad', type: 'scenario_classification', difficulty: 1, mode: 'practice', prompt: 'A fictional class grade file is changed accidentally. Which CIA triad area is most affected?', scenario: 'No real student data is used; this is a toy example.', options: ['Confidentiality', 'Integrity', 'Availability'], correctAnswer: 'Integrity', explanation: 'Integrity means information remains accurate and unaltered except through approved changes.', hints: ['Think accuracy.', 'Which part changes when data is incorrect?'], commonWrongAnswerExplanation: 'Confidentiality is about unwanted disclosure; availability is about access when needed.', relatedLessonSlug: 'cia-triad', relatedLabSlug: 'digital-safety-home-audit' },
  { id: 'ex-risk-ranking-1', skillId: 'cyber-risk-basics', type: 'risk_ranking', difficulty: 2, mode: 'practice', prompt: 'Rank the fictional risks by what the school should address first.', scenario: 'Toy pilot risks: missing parent safety note, unlabeled external links, typo in club flyer.', options: ['Missing parent safety note', 'Unlabeled external links', 'Typo in club flyer'], correctAnswer: ['Missing parent safety note', 'Unlabeled external links', 'Typo in club flyer'], explanation: 'Safety communication and unsafe external-link ambiguity create higher learner risk than a typo.', hints: ['Prioritize student safety and likelihood.', 'Communication gaps can create real confusion.'], commonWrongAnswerExplanation: 'Cosmetic issues matter less than safety and authorization clarity.', relatedLessonSlug: 'risk-assets-threats', relatedLabSlug: 'risk-register-review' },
  { id: 'ex-ethics-boundary-1', skillId: 'cyber-ethics-authorization', type: 'true_false', difficulty: 1, mode: 'review', prompt: 'True or false: It is acceptable to practice only in labs, toy examples, or systems where you have explicit authorization.', scenario: 'A learner wants a simple rule for practice boundaries.', options: ['true', 'false'], correctAnswer: 'true', explanation: 'CyberPath requires explicit authorization and safe fictional environments.', hints: ['The key phrase is explicit authorization.', 'Safe labs are intentionally scoped.'], commonWrongAnswerExplanation: 'Curiosity never replaces authorization.', relatedLessonSlug: 'what-is-cybersecurity' },
  { id: 'ex-authn-authz-1', skillId: 'iam-authentication', type: 'matching', difficulty: 1, mode: 'learn', prompt: 'Match each identity concept to its meaning.', scenario: 'A fictional club app is being explained to beginners.', options: ['Authentication', 'Authorization'], correctAnswer: { Authentication: 'Proves who you are', Authorization: 'Decides what you can access' }, explanation: 'Authentication verifies identity; authorization grants appropriate permissions after identity is known.', hints: ['AuthN asks who.', 'AuthZ asks allowed to do what.'], commonWrongAnswerExplanation: 'These terms are related but not interchangeable.', relatedLessonSlug: 'identity-access-basics' },
  { id: 'ex-least-privilege-1', skillId: 'iam-authorization', type: 'evidence_selection', difficulty: 2, mode: 'practice', prompt: 'Which evidence best supports reducing access?', scenario: 'Fictional account: newsletter-helper has admin role but only sends weekly emails.', options: ['Admin role assigned', 'Only sends weekly emails', 'Account name includes helper', 'Uses the club logo'], correctAnswer: ['Admin role assigned', 'Only sends weekly emails'], explanation: 'The evidence shows a mismatch between broad permissions and a narrow job need.', hints: ['Compare job need to permission.', 'Least privilege is about enough access, not maximum access.'], commonWrongAnswerExplanation: 'Names and logos do not prove access risk by themselves.', relatedLessonSlug: 'identity-access-basics', relatedLabSlug: 'access-control-review' },
  { id: 'ex-mfa-policy-1', skillId: 'iam-mfa-passwords', type: 'policy_review', difficulty: 2, mode: 'lab_prep', prompt: 'Choose the best defensive recommendation for a staff account policy.', scenario: 'Fictional policy says MFA is optional for mentors who can view student progress.', options: ['Require MFA for mentor/admin accounts', 'Ask students to share backup codes', 'Disable all password resets', 'Use one shared mentor account'], correctAnswer: 'Require MFA for mentor/admin accounts', explanation: 'Privileged accounts should use MFA; shared secrets or shared accounts create accountability and safety problems.', hints: ['Look for a practical safer control.', 'Never share backup codes.'], commonWrongAnswerExplanation: 'Shared access and secret sharing weaken accountability.', relatedLessonSlug: 'passwords-mfa-and-phishing', relatedLabSlug: 'password-policy-audit' },
  { id: 'ex-dns-http-log-1', skillId: 'net-ip-dns-http', type: 'log_interpretation', difficulty: 2, mode: 'learn', prompt: 'What does this toy log most directly show: GET /login 200 from 10.0.0.5?', scenario: 'Fictional local training log, not a real system.', options: ['A web request returned success', 'A password was stolen', 'A server was bypassed', 'Malware persistence was installed'], correctAnswer: 'A web request returned success', explanation: 'A 200 response means the request succeeded; the log alone does not prove theft, bypass, or malware.', hints: ['Interpret only what the evidence supports.', 'Avoid overclaiming.'], commonWrongAnswerExplanation: 'Defensive analysis should not claim incidents beyond the available evidence.', relatedLessonSlug: 'networking-fundamentals', relatedLabSlug: 'network-log-triage' },
  { id: 'ex-log-evidence-1', skillId: 'net-logs-flows', type: 'evidence_selection', difficulty: 2, mode: 'practice', prompt: 'Select the evidence that belongs in a triage note.', scenario: 'Toy DNS logs show repeated requests to updates.example.test from one classroom device.', options: ['Timestamp', 'Source device id', 'Domain requested', 'A guess about the student’s intent'], correctAnswer: ['Timestamp', 'Source device id', 'Domain requested'], explanation: 'Good notes include observable evidence and avoid unsupported claims about intent.', hints: ['Pick facts from the log.', 'Do not guess motive.'], commonWrongAnswerExplanation: 'Intent requires more evidence and should be phrased carefully.', relatedLessonSlug: 'networking-fundamentals', relatedLabSlug: 'network-log-triage' },
  { id: 'ex-linux-permissions-1', skillId: 'linux-files-permissions', type: 'multiple_choice', difficulty: 2, mode: 'practice', prompt: 'A toy file is readable by everyone but only mentors should read it. What is the defensive issue?', scenario: 'Fictional file permissions example.', options: ['Excessive read permission', 'A DNS issue', 'An availability improvement', 'A password reset problem'], correctAnswer: 'Excessive read permission', explanation: 'Permissions should match the people and roles that need access.', hints: ['Look at who can read.', 'Compare actual access to required access.'], commonWrongAnswerExplanation: 'This is about file access, not networking or password reset.', relatedLessonSlug: 'operating-systems-and-files', relatedLabSlug: 'linux-permissions-detective' },
  { id: 'ex-alert-triage-1', skillId: 'soc-alert-triage', type: 'report_writing', difficulty: 3, mode: 'mastery_challenge', prompt: 'Write a three-sentence triage note with evidence, risk, and safe next step.', scenario: 'Fictional alert: five failed logins then one success for demo-user from a new city in a toy dataset.', rubric: ['mentions failed logins and success', 'states uncertainty', 'recommends authorized account review/MFA check'], correctAnswer: 'Evidence-based note with uncertainty and authorized review.', explanation: 'A strong triage note separates evidence from interpretation and recommends safe authorized review.', hints: ['Sentence 1 evidence, sentence 2 risk, sentence 3 next step.', 'Do not claim compromise without proof.'], commonWrongAnswerExplanation: 'Overconfident claims and intrusive actions are not appropriate from limited evidence.', relatedLessonSlug: 'soc-alert-triage', relatedLabSlug: 'first-soc-alert-triage' },
  { id: 'ex-web-remediation-1', skillId: 'web-access-input-defense', type: 'short_answer', difficulty: 3, mode: 'practice', prompt: 'Name one safe remediation for a toy form that accepts unexpected characters and displays confusing errors.', scenario: 'Toy code review scenario; no exploit steps or real target.', correctAnswer: 'validate input', explanation: 'Input validation and clear server-side checks are defensive remediations.', hints: ['Focus on fixing, not exploiting.', 'The phrase input validation is enough.'], commonWrongAnswerExplanation: 'Defensive code review should recommend controls, tests, and clear errors, not attack steps.', relatedLessonSlug: 'web-security-defense', relatedLabSlug: 'safe-code-review' },
  { id: 'ex-cloud-iam-1', skillId: 'cloud-iam-roles', type: 'multi_select', difficulty: 3, mode: 'practice', prompt: 'Which changes improve a fictional cloud role safely?', scenario: 'Toy cloud account: report-generator has admin rights but only reads monthly billing summaries.', options: ['Replace admin with read-only billing scope', 'Document owner and review date', 'Store real keys in a class chat', 'Keep admin because it is convenient'], correctAnswer: ['Replace admin with read-only billing scope', 'Document owner and review date'], explanation: 'Least privilege and periodic review reduce risk without handling real secrets.', hints: ['Select all safe improvements.', 'Never share real keys.'], commonWrongAnswerExplanation: 'Convenience and secret sharing are not defensible security controls.', relatedLessonSlug: 'cloud-iam-basics', relatedLabSlug: 'mock-cloud-iam-review' },
  { id: 'ex-exec-summary-1', skillId: 'grc-risk-registers', type: 'report_writing', difficulty: 2, mode: 'practice', prompt: 'Write one executive-summary sentence for a fictional high-impact classroom safety risk.', scenario: 'Toy school pilot risk register.', rubric: ['plain language', 'risk impact', 'owner or next action'], correctAnswer: 'Plain-language risk sentence with owner and action.', explanation: 'Executives need concise risk, impact, and ownership, not technical jargon.', hints: ['Use plain language.', 'Include who should act.'], commonWrongAnswerExplanation: 'A summary without action is hard for leaders to use.', relatedLessonSlug: 'risk-registers-and-controls', relatedLabSlug: 'risk-register-review' },
  { id: 'ex-ai-boundary-1', skillId: 'ai-safe-use-boundaries', type: 'scenario_classification', difficulty: 1, mode: 'review', prompt: 'Which AI use is safe in CyberPath?', scenario: 'Classroom AI rules practice.', options: ['Ask for a glossary explanation using fictional data', 'Paste a classmate email into a prompt', 'Ask for steps against a real website', 'Upload private school records'], correctAnswer: 'Ask for a glossary explanation using fictional data', explanation: 'Safe AI use avoids private data, real targets, and harmful operational steps.', hints: ['Look for fictional data.', 'Private data stays out of prompts.'], commonWrongAnswerExplanation: 'Real personal data and real-target instructions are outside the platform safety model.', relatedLessonSlug: 'ai-security-awareness', relatedLabSlug: 'ai-security-awareness-scenario' }
];

export function isExerciseCorrect(exercise: Exercise, answer: unknown) {
  if (exercise.type === 'multi_select' || exercise.type === 'risk_ranking' || exercise.type === 'evidence_selection') {
    return JSON.stringify([...(exercise.correctAnswer as string[] || [])].sort()) === JSON.stringify([...(answer as string[] || [])].sort());
  }
  if (exercise.type === 'matching') {
    return JSON.stringify(exercise.correctAnswer) === JSON.stringify(answer);
  }
  if (exercise.type === 'short_answer') {
    return String(answer || '').toLowerCase().includes(String(exercise.correctAnswer || '').toLowerCase());
  }
  if (exercise.type === 'report_writing') {
    const text = String(answer || '').toLowerCase();
    return (exercise.rubric || []).filter((item) => text.includes(item.split(' ')[0].toLowerCase())).length >= 1 || text.length >= 80;
  }
  return JSON.stringify(exercise.correctAnswer) === JSON.stringify(answer);
}
