name: Deploy to Hugging Face Spaces

on:
  push:
    branches: [main, master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Git Configuration
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Sync and Filter Files
        run: |
          # 1. Vaqtincha toza papka ochamiz
          mkdir ../clean_project
          
          # 2. Loyihani taqiqlangan fayllarsiz o'sha papkaga ko'chiramiz
          rsync -av --progress . ../clean_project --exclude 'apps/server/data/*.db' --exclude 'apps/server/apps/server/data/*.db' --exclude 'apps/server/data/backups/' --exclude 'docs/assets/*.png' --exclude '.git'
          
          # 3. Hugging Face omborini shu erga klon qilamiz
          git clone https://madijonov111:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/madijonov111/cyberpath-academy ../hf_space
          
          # 4. Toza kodlarni u yerga o'tkazamiz
          rsync -av --delete ../clean_project/ ../hf_space/
          
          # 5. Hugging Face ichiga kirib, faqat toza kodni yuklaymiz
          cd ../hf_space
          git add .
          git commit -m "deploy: clean production build without binaries" || true
          git push origin main
